spring:
  config:
    import: 'optional:file:.local.env.properties'
  banner:
    location: 'banner.txt'
  datasource:
    url: 'jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}'
    username: '${DB_USERNAME}'
    password: '${DB_PASSWORD}'
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'

server:
  port: '${SERVER_PORT:8089}'