name: Build

on:
  push:
    branches:
      - test
    path-ignore:
      - "**/README.md"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
    
      - name: Build source
        run: ./gradlew clean build -x test

      - name: UnitTest
        run: ./gradlew clean unitTest