name: ci

on:
  push:
    branches:
      - test
    path-ignore:
      - "**/README.md"

jobs:
  test-build:
    name: Testing and Building
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
    
      # - name: Build and Test
      #   run: ./gradlew clean build
      #   env:
      #     DB_HOST: ${{ secrets.DB_HOST }}
      #     DB_DATABASE: ${{ secrets.DB_DATABASE }}
      #     DB_USER: ${{ secrets.DB_USER }}
      #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Build
        run: ./gradlew clean build -x test
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Test
        run: ./gradlew clean test --info